name:       "Duckmole - #FF For Fun"
description: "YAB: Yet Another Blog"
url: "http://fabrice.nourisson-pytel.fr"
baseurl: "http://fabrice.nourisson-pytel.fr"
author: "Fabrice Nourisson"
signoff:          Fabrice
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
links:
  - name:         /
    url:          /
  - name:         About
    url:          /about
  - name:         GitHub
    url:          http://github.com/duckmole
    external:     true
  - name:         "@duckmole"
    url:          http://twitter.com/duckmole
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
collections:
  - talks
