name: "Duckmole - Another jekyll pages "
description: "ServeBox - Technology Watch"
url: "http://duckmole.github.io"
baseurl: "http://duckmole.github.io"
author: "Fabrice Nourisson"
signoff:          Fabrice
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
links:
  - name:         /
    url:          /
  - name:         About
    url:          /about
  - name:         GitHub
    url:          http://github.com/duckmole
    external:     true
  - name:         "@duckmole"
    url:          http://twitter.com/duckmole
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
collections:
  - talks
